#!/usr/bin/env bash

BIN="$HOME/bin"
DIR="$(realpath .)"

if [ ! -d "$BIN" ]; then
    echo "creating directory: $BIN ..."
    mkdir "$BIN"
fi

FILES=(
    ".bashrc"
    ".bash_aliases"
    ".gitconfig"
    "bin/backup_world"
)
for FILE in "${FILES[@]}"; do
    if [ -f "$HOME/$FILE" ]; then
        echo "backing up $HOME/$FILE to $HOME/$FILE.old ..."
        cp "$HOME/$FILE" "$HOME/$FILE.old"
    fi
    echo "copying $DIR/$FILE to $HOME/$FILE ..."
    cp "$DIR/$FILE" "$HOME/$FILE"
done

echo "getting screenfetch-ubuntu..."
wget "https://raw.githubusercontent.com/cgoldberg/screenfetch-ubuntu/master/screenfetch-ubuntu" -O "$HOME/bin/screenfetch-ubuntu"
chmod +x "$HOME/bin/screenfetch-ubuntu"

echo "getting git-prompt.sh..."
wget "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh" -O "$HOME/bin/git-prompt.sh"
chmod +x "$HOME/bin/git-prompt.sh"

echo "getting git-completion.bash..."
wget "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash" -O "$HOME/bin/git-completion.bash"
chmod +x "$HOME/bin/git-completion.bash"

echo "done"
