[/]
close=['<Alt>F4']
switch-input-source=@as []
switch-input-source-backward=@as []
switch-to-workspace-left=@as []
switch-to-workspace-right=@as []
switch-applications=@as []
switch-applications-backward=@as []
switch-windows=['<Alt>Tab']
