[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom8/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom9/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom10/']
help=@as []
magnifier=@as []
magnifier-zoom-in=@as []
magnifier-zoom-out=@as []
screenreader=@as []

[custom-keybindings/custom0]
binding='F12'
command='/home/cgoldberg/bin/toggle-audio-sink'
name='Toggle Audio Sink'

[custom-keybindings/custom1]
binding='Pause'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-pause'
name='Squeezebox Pause/Play'

[custom-keybindings/custom10]
binding='<Control>Delete'
command='chromium "http://10.0.0.100:9000"'
name='Chrome (Lyrion)'

[custom-keybindings/custom2]
binding='<Control>Pause'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-next'
name='Squeezebox Next Track'

[custom-keybindings/custom3]
binding='<Shift><Control>Pause'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-mix'
name='Squeezebox Mix'

[custom-keybindings/custom4]
binding='<Control>Right'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-skip-forward'
name='Squeezebox Skip Forward 2 Mins'

[custom-keybindings/custom5]
binding='<Control>Left'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-skip-back'
name='Squeezebox Skip Back 30 Secs'

[custom-keybindings/custom6]
binding='<Control>Print'
command='/home/cgoldberg/bin/random-wallpaper'
name='Random Wallpaper'

[custom-keybindings/custom7]
binding='<Control>Page_Up'
command='gnome-terminal --geometry=90x100 -- bash -ic "stocks"'
name='Stock Charts'

[custom-keybindings/custom8]
binding='<Control>Page_Down'
command='gnome-terminal'
name='Terminal'

[custom-keybindings/custom9]
binding='<Control>Insert'
command='chromium "https://github.com"'
name='Chrome (GitHub)'
