[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']
help=@as []
magnifier=@as []
magnifier-zoom-in=@as []
magnifier-zoom-out=@as []
screenreader=@as []

[custom-keybindings/custom0]
binding='F12'
command='/home/cgoldberg/bin/toggle-audio-sink'
name='Toggle Audio Sink'

[custom-keybindings/custom1]
binding='Pause'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-pause'
name='Squeezebox Pause/Play'

[custom-keybindings/custom2]
binding='<Control>Pause'
command='/home/cgoldberg/bin/squeezebox-function squeezebox-next'
name='Squeezebox Next Track'
